services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Password@1"
      MYSQL_DATABASE: "duan0"
    ports:
      - 3308:3306
    volumes:
      - mysql_data_container:/var/lib/mysql

volumes:
  mysql_data_container:

    # docker compose -p du-an-0 up -d
